#!/usr/bin/python3

def raise_exception_msg(message=""):
    """name error with a message"""
    raise NameError(message)
